routes/web.php
<?php

use App\Http\Controllers\BirthdayController;
use App\Http\Controllers\CalendarController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\RoutineController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login.form');
});
Route::middleware('guest')->controller(UserController::class)->group(function () {
    Route::prefix('/register')->group(function () {
        Route::get('/', 'create')->name('registration.form');
        Route::post('/', 'store')->name('register');
    });
    Route::prefix('/login')->group(function () {
        Route::view('/', 'auth.login')->name('login.form');
        Route::post('/', 'login')->name('login');
    });
});

Route::middleware('auth')->group(function () {
    Route::get('/logout', [UserController::class, 'logout'])->name('logout');
    Route::delete('/events/delete-past', [EventController::class, 'deletePast'])->name('events.delete-past');
    Route::resource('events', EventController::class)->except(['show']);
    Route::resource('routines', RoutineController::class)->except(['show']);
    Route::resource('birthdays', BirthdayController::class)->except(['show']);
    Route::resource('categories', CategoryController::class)->except(['show']);
    Route::put('/tasks/{id}/toggle-finished', [TaskController::class, 'toggleFinished']);
    Route::delete('/tasks/delete-finished', [TaskController::class, 'deleteFinished'])->name('tasks.delete-finished');
    Route::resource('tasks', TaskController::class)->except(['show']);
    Route::view('/help', 'dashboard.help')->name('help');
    Route::get('/calendar', [CalendarController::class, 'index'])->name('calendar');
    Route::prefix('/notifications')
        ->name('notifications.')
        ->controller(NotificationController::class)
        ->group(function() {
            Route::get('/', 'index')->name('index');
            Route::put('/{id}/confirm', 'confirm')->name('confirm');
            Route::delete('/clear', 'clear')->name('clear');
        });
});

app/Models/Enums/EventType.php
<?php

namespace App\Models\Enums;

enum EventType: string
{
    case BIRTHDAY = 'birthday';
    case EVENT = 'event';
    case ROUTINE = 'routine';
}

app/Models/Event.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;

/**
 * @property int $id
 * @property string $description
 * @property Carbon $starts_at
 * @property int $user_id
 * @property-read User $user
 */
class Event extends Model
{
    use HasFactory;

    public $timestamps = false;
    protected $casts = [
        'starts_at' => 'datetime'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use App\Http\Dto\Requests\Event\EventFilters;
use App\Http\Dto\Requests\Event\EventForm;
use App\Service\Event\IEventService;
use Carbon\Carbon;
use Illuminate\Http\Request;

class EventController extends Controller
{
    public function __construct(
        private IEventService $eventService
    )
    {
    }

    /**
     * Display a listing of the resource.
     *
     */
    public function index(Request $request)
    {
        if ($request->hasCookie('eventFilters_dateFrom') &&
            $request->hasCookie('eventFilters_dateTo')) {
            $filters = new EventFilters(
                Carbon::createFromIsoFormat('Y-MM-DD', $request->cookie('eventFilters_dateFrom'))->startOfDay(),
                Carbon::createFromIsoFormat('Y-MM-DD', $request->cookie('eventFilters_dateTo'))->endOfDay()
            );
        } else {
            $filters = null;
        }
        $result = $this->eventService->getEventsList($filters);
        return view('registry.events.events-list', compact('result'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('registry.events.new-edit-event', ['id' => -1]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     */
    public function store(Request $request)
    {
        $request->validate([
            'description' => 'required|string|max:255|min:1',
            'startsAt' => 'required|date|after:now'
        ]);
        $this->eventService->createOrUpdateEvent(
            new EventForm(null, $request->description, $request->startsAt)
        );
        return redirect()->route('events.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     */
    public function edit($id)
    {
        $event = $this->eventService->getEventEditor($id);
        return view('registry.events.new-edit-event', compact('id', 'event'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'description' => 'required|string|max:255|min:1',
            'startsAt' => 'required|date|after:now'
        ]);
        $this->eventService->createOrUpdateEvent(
            new EventForm($id, $request->description, $request->startsAt)
        );
        return redirect()->route('events.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     */
    public function destroy($id)
    {
        $this->eventService->deleteEvent($id);
        return redirect()->back();
    }

    public function deletePast()
    {
        $this->eventService->deletePastEvents();
        return redirect()->back();
    }
}

resources/views/registry/events/events-list.blade.php
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title>SUETA - Список мероприятий</title>
    <link rel="stylesheet" href="{{asset('assets/css/navbar.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/controls.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/list-table.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/events-list.css')}}">
    <link rel="shortcut icon" href="{{asset('favicon.ico')}}">
    <script type="module" src="{{asset('assets/compiled-js/events-list.js')}}"></script>
</head>
<body>
<div class="wrapper">
    @include('components.navbar')
    <div class="main-area">
        <div class="flex-right">
            <form action="{{route('events.create')}}">
                <button type="submit" class="dark-create-button button-icon-flex mr">
                    <img src="{{asset('assets/img/icons/plus.png')}}">
                    <span>
                        Новое мероприятие
                    </span>
                </button>
            </form>
            <form method="post" action="{{route('events.delete-past')}}">
                @method('DELETE')
                @csrf
                <button id="btn-delete-past-events" type="button"
                        class="dark-cancel-button button-icon-flex">
                    <img src="{{asset('assets/img/icons/trash.png')}}">
                    <span>
                    Удалить прошедшие
                </span>
                </button>
            </form>
        </div>
        <div>
            <form name="dateFiltersForm" class="flex-center">
                <span class="input-label mr">
                    с
                </span>
                <input type="date" name="dateFrom" required class="mr dark-text-input dark-datetime-input">
                <span class="input-label mr">
                    по
                </span>
                <input type="date" name="dateTo" required class="mr dark-text-input dark-datetime-input">
                <button id="btn-apply-filters" type="button" class="dark-button mr">
                    Фильтровать
                </button>
                <button id="btn-reset-filters" type="button" class="dark-cancel-button">
                    Сбросить
                </button>
            </form>
        </div>
        @if (count($result->events) == 0)
            <div class="empty-message-flex">
                <div class="empty-message">
                    Мероприятия отсутствуют
                </div>
            </div>
        @else
            <div class="flex-center">
                <table class="list-table">
                    <thead>
                    <tr>
                        <td>
                            Описание
                        </td>
                        <td>
                            Начало
                        </td>
                        <td></td>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($result->events as $event)
                        <tr>
                            <td>
                                {{$event->description}}
                            </td>
                            <td>
                                {{$event->startsAt}}
                            </td>
                            <td class="buttons-cell">
                                <form method="get" action="{{route('events.edit', ['event' => $event->id])}}"
                                    class="inline">
                                    <button type="submit" class="dark-button tight-button">
                                        <img src="{{asset('assets/img/icons/edit.png')}}">
                                    </button>
                                </form>
                                <form method="post" action="{{route('events.destroy', ['event' => $event->id])}}"
                                    class="inline">
                                    @method('DELETE')
                                    @csrf
                                    <button id="btn-delete-event-{{$event->id}}" type="button"
                                            class="dark-button tight-button ml">
                                        <img src="{{asset('assets/img/icons/delete.png')}}">
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        @endif
    </div>
</div>
</body>
</html>

resources/views/registry/events/new-edit-event.blade.php
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title>SUETA - Мероприятие</title>
    <link rel="stylesheet" href="{{asset('assets/css/navbar.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/controls.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/new-edit-event.css')}}">
    <link rel="shortcut icon" href="{{asset('favicon.ico')}}">
    <script defer src="{{asset('assets/compiled-js/cancel-button.js')}}"></script>
</head>
@php
    $isCreating = ($id == -1);
    $isUpdating = !$isCreating;
@endphp
<body>
<div class="wrapper">
    @include('components.navbar')
    <div class="main-area">
        <form method="post" autocomplete="off"
              @if ($isCreating)
                  action="{{route('events.store')}}"
              @else
                  action="{{route('events.update', ['event' => $id])}}"
              @endif
              class="event-form">
            @if ($isUpdating)
                @method('PUT')
            @endif
            @include('components.form-errors')
            @csrf
            <div class="flex-center">
                <div>
                    <div class="input-label">
                        Описание мероприятия
                    </div>
                    <div>
                        <input name="description" type="text"
                               @if ($isCreating || $errors->any())
                                   value="{{old('description')}}"
                               @else
                                   value="{{$event->description}}"
                               @endif
                               class="dark-text-input input-width" required>
                    </div>
                    <div class="input-label">
                        Дата и время начала
                    </div>
                    <div>
                        <input name="startsAt" type="datetime-local"
                               @if ($isCreating || $errors->any())
                                   value="{{old('startsAt')}}"
                               @else
                                   value="{{$event->startsAt}}"
                               @endif
                               class="dark-text-input dark-datetime-input input-width" required>
                    </div>
                    <div class="buttons-flex">
                        <button type="submit" class="dark-button">
                            Сохранить
                        </button>
                        <button id="btn-cancel" type="button" class="dark-cancel-button">
                            Отмена
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
</body>
</html>