routes/web.php
<?php

use App\Http\Controllers\BirthdayController;
use App\Http\Controllers\CalendarController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\RoutineController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login.form');
});
Route::middleware('guest')->controller(UserController::class)->group(function () {
    Route::prefix('/register')->group(function () {
        Route::get('/', 'create')->name('registration.form');
        Route::post('/', 'store')->name('register');
    });
    Route::prefix('/login')->group(function () {
        Route::view('/', 'auth.login')->name('login.form');
        Route::post('/', 'login')->name('login');
    });
});

Route::middleware('auth')->group(function () {
    Route::get('/logout', [UserController::class, 'logout'])->name('logout');
    Route::delete('/events/delete-past', [EventController::class, 'deletePast'])->name('events.delete-past');
    Route::resource('events', EventController::class)->except(['show']);
    Route::resource('routines', RoutineController::class)->except(['show']);
    Route::resource('birthdays', BirthdayController::class)->except(['show']);
    Route::resource('categories', CategoryController::class)->except(['show']);
    Route::put('/tasks/{id}/toggle-finished', [TaskController::class, 'toggleFinished']);
    Route::delete('/tasks/delete-finished', [TaskController::class, 'deleteFinished'])->name('tasks.delete-finished');
    Route::resource('tasks', TaskController::class)->except(['show']);
    Route::view('/help', 'dashboard.help')->name('help');
    Route::get('/calendar', [CalendarController::class, 'index'])->name('calendar');
    Route::prefix('/notifications')
        ->name('notifications.')
        ->controller(NotificationController::class)
        ->group(function() {
            Route::get('/', 'index')->name('index');
            Route::put('/{id}/confirm', 'confirm')->name('confirm');
            Route::delete('/clear', 'clear')->name('clear');
        });
});

app/Models/Routine.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;

/**
 * @property int $id
 * @property string $description
 * @property Carbon $count_start_date
 * @property int $period_length_days
 * @property int $user_id
 * @property-read User $user
 */
class Routine extends Model
{
    use HasFactory;

    public $timestamps = false;
    protected $casts = [
        'count_start_date' => 'datetime'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/RoutineController.php
<?php

namespace App\Http\Controllers;

use App\Http\Dto\Requests\Routine\RoutineForm;
use App\Service\Routine\IRoutineService;
use Illuminate\Http\Request;

class RoutineController extends Controller
{
    public function __construct(
        private IRoutineService $routineService
    )
    {
    }

    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $result = $this->routineService->getRoutinesList();
        return view('registry.routines.routines-list', compact('result'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('registry.routines.new-edit-routine', ['id' => -1]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     */
    public function store(Request $request)
    {
        $request->validate([
            'description' => 'required|string|max:255|min:1',
            'countStartDate' => 'required|date',
            'periodLengthDays' => 'required|integer|min:1'
        ]);
        $this->routineService->createOrUpdateRoutine(
            new RoutineForm(
                null,
                $request->description,
                $request->countStartDate,
                $request->periodLengthDays
            )
        );
        return redirect()->route('routines.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     */
    public function edit($id)
    {
        $routine = $this->routineService->getRoutineEditor($id);
        return view('registry.routines.new-edit-routine', compact('id', 'routine'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'description' => 'required|string|max:255|min:1',
            'countStartDate' => 'required|date',
            'periodLengthDays' => 'required|integer|min:1'
        ]);
        $this->routineService->createOrUpdateRoutine(
            new RoutineForm(
                $id,
                $request->description,
                $request->countStartDate,
                $request->periodLengthDays
            )
        );
        return redirect()->route('routines.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     */
    public function destroy($id)
    {
        $this->routineService->deleteRoutine($id);
        return redirect()->back();
    }
}

resources/views/registry/routines/new-edit-routine.blade.php
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title>SUETA - Рутина</title>
    <link rel="stylesheet" href="{{asset('assets/css/navbar.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/controls.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/new-edit-routine.css')}}">
    <link rel="shortcut icon" href="{{asset('favicon.ico')}}">
    <script defer src="{{asset('assets/compiled-js/cancel-button.js')}}"></script>
</head>
@php
    $isCreating = ($id == -1);
    $isUpdating = !$isCreating;
@endphp
<body>
<div class="wrapper">
    @include('components.navbar')
    <div class="main-area">
        <form method="post" autocomplete="off"
              @if($isCreating)
                  action="{{route('routines.store')}}"
              @else
                  action="{{route('routines.update', ['routine' => $id])}}"
              @endif
              class="routine-form">
            @csrf
            @if ($isUpdating)
                @method('PUT')
            @endif
            @include('components.form-errors')
            <div class="flex-center">
                <div>
                    <div class="input-label">
                        Описание рутины
                    </div>
                    <div>
                        <input name="description" type="text"
                               @if ($isCreating || $errors->any())
                                   value="{{old('description')}}"
                               @else
                                   value="{{$routine->description}}"
                               @endif
                               class="dark-text-input input-width" required>
                    </div>
                    <div class="input-label">
                        Дата начала отсчёта
                    </div>
                    <div>
                        <input name="countStartDate" type="date"
                               @if($isCreating || $errors->any())
                                   value="{{old('countStartDate')}}"
                               @else
                                   value="{{$routine->countStartDate}}"
                               @endif
                               class="dark-text-input dark-datetime-input input-width" required>
                    </div>
                    <div class="input-label">
                        Периодичность в днях
                    </div>
                    <div>
                        <input name="periodLengthDays" type="number"
                               @if($isCreating || $errors->any())
                                   value="{{old('periodLengthDays')}}"
                               @else
                                   value="{{$routine->periodLengthDays}}"
                               @endif
                               class="dark-text-input" min="1" required>
                    </div>
                    <div class="buttons-flex">
                        <button type="submit" class="dark-button">
                            Сохранить
                        </button>
                        <button id="btn-cancel" type="button" class="dark-cancel-button">
                            Отмена
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
</body>
</html>

resources/views/registry/routines/routines-list.blade.php
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title>SUETA - Список рутины</title>
    <link rel="stylesheet" href="{{asset('assets/css/navbar.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/controls.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/list-table.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/routines-list.css')}}">
    <link rel="shortcut icon" href="{{asset('favicon.ico')}}">
    <script defer src="{{asset('assets/compiled-js/routines-list.js')}}"></script>
</head>
<body>
<div class="wrapper">
    @include('components.navbar')
    <div class="main-area">
        <div class="flex-right">
            <form method="get" action="{{route('routines.create')}}">
                <button type="submit" class="dark-create-button button-icon-flex">
                    <img src="{{asset('assets/img/icons/plus.png')}}">
                    <span>
                        Новая рутина
                    </span>
                </button>
            </form>
        </div>
        @if(count($result->routines) == 0)
            <div class="empty-message-flex">
                <div class="empty-message">
                    Рутина отсутствует
                </div>
            </div>
        @else
            <div class="flex-center">
                <table class="list-table">
                    <thead>
                    <tr>
                        <td>
                            Описание
                        </td>
                        <td>
                            Отсчёт с
                        </td>
                        <td>
                            Периодичность в днях
                        </td>
                        <td></td>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($result->routines as $routine)
                        <tr>
                            <td>
                                {{$routine->description}}
                            </td>
                            <td>
                                {{$routine->countStartDate}}
                            </td>
                            <td class="centered-cell">
                                {{$routine->periodLengthDays}}
                            </td>
                            <td class="buttons-cell">
                                <form method="get" action="{{route('routines.edit', ['routine' => $routine->id])}}"
                                    class="inline">
                                    <button type="submit" class="dark-button tight-button">
                                        <img src="{{asset('assets/img/icons/edit.png')}}">
                                    </button>
                                </form>
                                <form method="post" action="{{route('routines.destroy', ['routine' => $routine->id])}}"
                                    class="inline">
                                    @method('DELETE')
                                    @csrf
                                    <button id="btn-delete-routine-{{$routine->id}}" type="button"
                                            class="dark-button tight-button ml">
                                        <img src="{{asset('assets/img/icons/delete.png')}}">
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        @endif
    </div>
</div>
</body>
</html>