routes/web.php
<?php

use App\Http\Controllers\BirthdayController;
use App\Http\Controllers\CalendarController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\RoutineController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login.form');
});
Route::middleware('guest')->controller(UserController::class)->group(function () {
    Route::prefix('/register')->group(function () {
        Route::get('/', 'create')->name('registration.form');
        Route::post('/', 'store')->name('register');
    });
    Route::prefix('/login')->group(function () {
        Route::view('/', 'auth.login')->name('login.form');
        Route::post('/', 'login')->name('login');
    });
});

Route::middleware('auth')->group(function () {
    Route::get('/logout', [UserController::class, 'logout'])->name('logout');
    Route::delete('/events/delete-past', [EventController::class, 'deletePast'])->name('events.delete-past');
    Route::resource('events', EventController::class)->except(['show']);
    Route::resource('routines', RoutineController::class)->except(['show']);
    Route::resource('birthdays', BirthdayController::class)->except(['show']);
    Route::resource('categories', CategoryController::class)->except(['show']);
    Route::put('/tasks/{id}/toggle-finished', [TaskController::class, 'toggleFinished']);
    Route::delete('/tasks/delete-finished', [TaskController::class, 'deleteFinished'])->name('tasks.delete-finished');
    Route::resource('tasks', TaskController::class)->except(['show']);
    Route::view('/help', 'dashboard.help')->name('help');
    Route::get('/calendar', [CalendarController::class, 'index'])->name('calendar');
    Route::prefix('/notifications')
        ->name('notifications.')
        ->controller(NotificationController::class)
        ->group(function() {
            Route::get('/', 'index')->name('index');
            Route::put('/{id}/confirm', 'confirm')->name('confirm');
            Route::delete('/clear', 'clear')->name('clear');
        });
});

app/Models/Birthday.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * @property int $id
 * @property string $person_name
 * @property string|null $person_photo_path
 * @property Carbon $date
 * @property boolean $is_year_unknown
 * @property int $user_id
 * @property-read User $user
 */
class Birthday extends Model
{
    use HasFactory;

    public $timestamps = false;
    protected $casts = [
        'date' => 'datetime'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/BirthdayController.php
<?php

namespace App\Http\Controllers;

use App\Http\Dto\Requests\Birthday\BirthdayFilters;
use App\Http\Dto\Requests\Birthday\BirthdayForm;
use App\Models\Enums\BirthdaySorting;
use App\Service\Birthday\IBirthdayService;
use Illuminate\Http\Request;
use Illuminate\Validation\Rules\File;

class BirthdayController extends Controller
{
    public function __construct(
        private IBirthdayService $birthdayService
    )
    {
    }

    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        $sortBy = BirthdaySorting::PERSON_NAME;
        if ($request->hasCookie('birthdayFilters_sortBy')) {
            $sortBy = BirthdaySorting::from($request->cookie('birthdayFilters_sortBy'));
        }
        $result = $this->birthdayService->getBirthdaysList(
            new BirthdayFilters($sortBy)
        );
        return view('registry.birthdays.birthdays-list', compact('result'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('registry.birthdays.new-edit-birthday', ['id' => -1]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     */
    public function store(Request $request)
    {
        $request->validate([
            'personName' => 'required|string|max:255|min:1',
            'personPhoto' => ['sometimes', File::image()->max(10 * 1024)],
            'isYearUnknown' => 'sometimes|accepted',
            'date' => 'exclude_if:isYearUnknown,on|date|before:now'
        ]);
        $this->birthdayService->createOrUpdateBirthday(
            new BirthdayForm(
                null,
                $request->personName,
                $request->file('personPhoto'),
                $request->date,
                $request->boolean('isYearUnknown')
            )
        );
        return redirect()->route('birthdays.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     */
    public function edit($id)
    {
        $birthday = $this->birthdayService->getBirthdayEditor($id);
        return view('registry.birthdays.new-edit-birthday', compact('id', 'birthday'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'personName' => 'required|string|max:255|min:1',
            'personPhoto' => ['sometimes', File::image()->max(10 * 1024)],
            'isYearUnknown' => 'sometimes|accepted',
            'date' => 'exclude_if:isYearUnknown,on|date|before:now'
        ]);
        $this->birthdayService->createOrUpdateBirthday(
            new BirthdayForm(
                $id,
                $request->personName,
                $request->file('personPhoto'),
                $request->date,
                $request->boolean('isYearUnknown')
            )
        );
        return redirect()->route('birthdays.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     */
    public function destroy($id)
    {
        $this->birthdayService->deleteBirthday($id);
        return redirect()->back();
    }
}

resources/views/registry/birthdays/birthdays-list.blade.php
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title>SUETA - Список дней рождения</title>
    <link rel="stylesheet" href="{{asset('assets/css/navbar.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/controls.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/list-table.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/birthdays-list.css')}}">
    <link rel="shortcut icon" href="{{asset('favicon.ico')}}">
    <script type="module" src="{{asset('assets/compiled-js/birthdays-list.js')}}"></script>
</head>
<body>
<div class="wrapper">
    @include('components.navbar')
    <div class="main-area">
        <div class="flex-between">
            <div @class(['hidden' => empty($result->birthdays)])>
                <span class="input-label">
                    Сортировать по
                </span>
                <select id="sorting-select" class="dark-select">
                    <option value="{{\App\Models\Enums\BirthdaySorting::PERSON_NAME->value}}">
                        имени
                    </option>
                    <option value="{{\App\Models\Enums\BirthdaySorting::DAY_AND_MONTH->value}}">
                        дню и месяцу рождения
                    </option>
                </select>
            </div>
            <form method="get" action="{{route('birthdays.create')}}">
                <button type="submit" class="dark-create-button button-icon-flex">
                    <img src="{{asset('assets/img/icons/plus.png')}}">
                    <span>
                        Новый день рождения
                    </span>
                </button>
            </form>
        </div>
        @if(count($result->birthdays) == 0)
            <div class="empty-message-flex">
                <div class="empty-message">
                    Дни рождения отсутствуют
                </div>
            </div>
        @else
            <div class="flex-center">
                <table class="list-table">
                    <thead>
                    <tr>
                        <td>
                            Имя
                        </td>
                        <td>
                            Фото
                        </td>
                        <td>
                            Дата рождения
                        </td>
                        <td>
                            Возраст
                        </td>
                        <td></td>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($result->birthdays as $birthday)
                        <tr>
                            <td>
                                {{$birthday->personName}}
                            </td>
                            <td class="centered-cell">
                                @isset($birthday->photoUrl)
                                    <img class="person-photo" src="{{$birthday->photoUrl}}">
                                @endisset
                            </td>
                            <td class="centered-cell">
                                {{$birthday->date}}
                            </td>
                            <td class="centered-cell">
                                @isset($birthday->age)
                                    {{$birthday->age}}
                                @endisset
                            </td>
                            <td class="buttons-cell">
                                <form method="get" action="{{route('birthdays.edit', ['birthday' => $birthday->id])}}"
                                      class="inline">
                                    <button type="submit" class="dark-button tight-button">
                                        <img src="{{asset('assets/img/icons/edit.png')}}">
                                    </button>
                                </form>
                                <form method="post"
                                      action="{{route('birthdays.destroy', ['birthday' => $birthday->id])}}"
                                      class="inline">
                                    @method('DELETE')
                                    @csrf
                                    <button id="btn-delete-birthday-{{$birthday->id}}"
                                            type="button" class="dark-button tight-button ml">
                                        <img src="{{asset('assets/img/icons/delete.png')}}">
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        @endif
    </div>
</div>
</body>
</html>

resources/views/registry/birthdays/new-edit-birthday.blade.php
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title>SUETA - День рождения</title>
    <link rel="stylesheet" href="{{asset('assets/css/navbar.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/controls.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/new-edit-birthday.css')}}">
    <link rel="shortcut icon" href="{{asset('favicon.ico')}}">
    <script defer src="{{asset('assets/compiled-js/cancel-button.js')}}"></script>
</head>
@php
    $isCreating = ($id == -1);
    $isUpdating = !$isCreating;
@endphp
<body>
<div class="wrapper">
    @include('components.navbar')
    <div class="main-area">
        <form method="post"
              @if ($isCreating)
                  action="{{route('birthdays.store')}}"
              @else
                  action="{{route('birthdays.update', ['birthday' => $id])}}"
              @endif
              enctype="multipart/form-data"
              autocomplete="off" class="birthday-form">
            @if ($isUpdating)
                @method('PUT')
            @endif
            @include('components.form-errors')
            @csrf
            <div class="flex-center">
                <div>
                    <div class="input-label">
                        Имя человека
                    </div>
                    <div>
                        <input name="personName" type="text"
                               @if ($isCreating || $errors->any())
                                   value="{{old('personName')}}"
                               @else
                                   value="{{$birthday->personName}}"
                               @endif
                               class="dark-text-input input-width" required>
                    </div>
                    <div class="input-label">
                        Фото (необязательно)
                    </div>
                    @if($isUpdating)
                        <div class="field-description">
                            (чтобы оставить существующее фото, <br> оставьте поле пустым)
                        </div>
                    @endif
                    <div class="file-input-flex">
                        <input name="personPhoto" type="file" accept=".jpg,.jpeg,.png">
                    </div>
                    <div class="input-label">
                        Дата рождения
                    </div>
                    <div class="field-description">
                        (если год неизвестен, укажите любой и поставьте галочку)
                    </div>
                    <div>
                        <input name="isYearUnknown" type="checkbox"
                               @if ($isCreating || $errors->any())
                                   @checked(old('isYearUnknown'))
                               @else
                                   @checked($birthday->isYearUnknown)
                               @endif
                               class="dark-checkbox">
                        <input name="date" type="date"
                               @if ($isCreating || $errors->any())
                                   value="{{old('date')}}"
                               @else
                                   value="{{$birthday->date}}"
                               @endif
                               class="dark-text-input dark-datetime-input input-width" required>
                    </div>
                    <div class="buttons-flex">
                        <button type="submit" class="dark-button">
                            Сохранить
                        </button>
                        <button id="btn-cancel" type="button" class="dark-cancel-button">
                            Отмена
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
</body>
</html>