routes/web.php
<?php

use App\Http\Controllers\BirthdayController;
use App\Http\Controllers\CalendarController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\RoutineController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login.form');
});
Route::middleware('guest')->controller(UserController::class)->group(function () {
    Route::prefix('/register')->group(function () {
        Route::get('/', 'create')->name('registration.form');
        Route::post('/', 'store')->name('register');
    });
    Route::prefix('/login')->group(function () {
        Route::view('/', 'auth.login')->name('login.form');
        Route::post('/', 'login')->name('login');
    });
});

Route::middleware('auth')->group(function () {
    Route::get('/logout', [UserController::class, 'logout'])->name('logout');
    Route::delete('/events/delete-past', [EventController::class, 'deletePast'])->name('events.delete-past');
    Route::resource('events', EventController::class)->except(['show']);
    Route::resource('routines', RoutineController::class)->except(['show']);
    Route::resource('birthdays', BirthdayController::class)->except(['show']);
    Route::resource('categories', CategoryController::class)->except(['show']);
    Route::put('/tasks/{id}/toggle-finished', [TaskController::class, 'toggleFinished']);
    Route::delete('/tasks/delete-finished', [TaskController::class, 'deleteFinished'])->name('tasks.delete-finished');
    Route::resource('tasks', TaskController::class)->except(['show']);
    Route::view('/help', 'dashboard.help')->name('help');
    Route::get('/calendar', [CalendarController::class, 'index'])->name('calendar');
    Route::prefix('/notifications')
        ->name('notifications.')
        ->controller(NotificationController::class)
        ->group(function() {
            Route::get('/', 'index')->name('index');
            Route::put('/{id}/confirm', 'confirm')->name('confirm');
            Route::delete('/clear', 'clear')->name('clear');
        });
});

app/Models/Task.php
<?php

namespace App\Models;

use App\Models\Enums\TaskPriority;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * @property int $id
 * @property TaskPriority $priority
 * @property string $description
 * @property string|null $photo_file_name
 * @property boolean $is_finished
 * @property int $category_id
 * @property-read Category $category
 */
class Task extends Model
{
    use HasFactory;

    public $timestamps = false;
    protected $casts = [
        'priority' => TaskPriority::class
    ];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Http\Dto\Requests\Task\TaskFilters;
use App\Http\Dto\Requests\Task\TaskForm;
use App\Models\Birthday;
use App\Models\Enums\TaskPriority;
use App\Models\Task;
use App\Service\Task\ICategoryService;
use App\Service\Task\ITaskService;
use Illuminate\Http\Request;
use Illuminate\Support\Benchmark;
use Illuminate\Validation\Rules\Enum;
use Illuminate\Validation\Rules\File;

class TaskController extends Controller
{
    public function __construct(
        private ITaskService $taskService,
        private ICategoryService $categoryService
    )
    {
    }

    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        $onlyFinished = false;
        $categoryId = null;
        if ($request->hasCookie('taskFilters_onlyFinished')) {
            $onlyFinished = $request->cookie('taskFilters_onlyFinished');
        }
        if ($request->hasCookie('taskFilters_categoryId') && $request->cookie('taskFilters_categoryId') !== 'null') {
            $categoryId = $request->cookie('taskFilters_categoryId');
        }
        $catalog = $this->taskService->getTasksCatalog(
            new TaskFilters($onlyFinished, $categoryId)
        );
        $categoriesList = $this->categoryService->getCategoriesSelectList();
        return view('registry.tasks.tasks-list', compact('catalog', 'categoriesList'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $categoriesList = $this->categoryService->getCategoriesSelectList();
        return view('registry.tasks.new-edit-task', ['id' => -1, ...compact('categoriesList')]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     */
    public function store(Request $request)
    {
        $request->validate([
            'categoryId' => 'required|int|exists:categories,id',
            'priority' => ['required', new Enum(TaskPriority::class)],
            'description' => 'required|string|max:2048|min:1',
            'photo' => ['sometimes', File::image()->max(10 * 1024)],
        ]);
        $this->taskService->createOrUpdateTask(
            new TaskForm(
                null,
                $request->categoryId,
                TaskPriority::from($request->priority),
                $request->description,
                $request->file('photo')
            )
        );
        return redirect()->route('tasks.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     */
    public function edit($id)
    {
        $task = $this->taskService->getTaskEditor($id);
        $categoriesList = $this->categoryService->getCategoriesSelectList();
        return view('registry.tasks.new-edit-task', compact('id', 'task', 'categoriesList'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'categoryId' => 'required|int|exists:categories,id',
            'priority' => ['required', new Enum(TaskPriority::class)],
            'description' => 'required|string|max:2048|min:1',
            'photo' => ['sometimes', File::image()->max(10 * 1024)],
        ]);
        $this->taskService->createOrUpdateTask(
            new TaskForm(
                $id,
                $request->categoryId,
                TaskPriority::from($request->priority),
                $request->description,
                $request->file('photo')
            )
        );
        return redirect()->route('tasks.index');
    }

    public function toggleFinished($id): void
    {
        $this->taskService->toggleTaskFinished($id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     */
    public function destroy($id)
    {
        $this->taskService->deleteTask($id);
        return redirect()->back();
    }

    public function deleteFinished()
    {
        $this->taskService->deleteFinishedTasks();
        return redirect()->back();
    }
}

resources/views/registry/tasks/new-edit-task-category.blade.php
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title>SUETA - Категория</title>
    <link rel="stylesheet" href="{{asset('assets/css/navbar.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/controls.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/new-edit-task-category.css')}}">
    <link rel="shortcut icon" href="{{asset('favicon.ico')}}">
    <script defer src="{{asset('assets/compiled-js/cancel-button.js')}}"></script>
</head>
@php
    $isCreating = ($id == -1);
    $isUpdating = !$isCreating;
@endphp
<body>
<div class="wrapper">
    @include('components.navbar')
    <div class="main-area">
        <form method="post"
              @if($isCreating)
                  action="{{route('categories.store')}}"
              @else
                  action="{{route('categories.update', ['category' => $id])}}"
              @endif
              autocomplete="off" class="category-form">
            @csrf
            @if ($isUpdating)
                @method('PUT')
            @endif
            @include('components.form-errors')
            <div class="flex-center">
                <div>
                    <div class="input-label">
                        Название
                    </div>
                    <div>
                        <input name="name" type="text"
                               @if ($isCreating || $errors->any())
                                   value="{{old('name')}}"
                               @else
                                   value="{{$category->name}}"
                               @endif
                               class="dark-text-input input-width" required>
                    </div>
                    <div class="input-label">
                        Цвет
                    </div>
                    <div class="color-input-flex">
                        <input name="backgroundColor" type="color"
                               @if($errors->any())
                                   value="{{old('backgroundColor')}}"
                               @elseif($isCreating)
                                   value="{{'#' . base_convert(random_int(0, 16_777_215), 10, 16)}}"
                               @else
                                   value="{{$category->backgroundColor}}"
                               @endif
                               required>
                    </div>
                    <div class="buttons-flex">
                        <button type="submit" class="dark-button">
                            Сохранить
                        </button>
                        <button id="btn-cancel" type="button" class="dark-cancel-button">
                            Отмена
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
</body>
</html>

resources/views/registry/tasks/task-categories-list.blade.php
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title>SUETA - Список категорий</title>
    <link rel="stylesheet" href="{{asset('assets/css/navbar.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/controls.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/list-table.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/task-categories-list.css')}}">
    <link rel="shortcut icon" href="{{asset('favicon.ico')}}">
    <script defer src="{{asset('assets/compiled-js/task-categories-list.js')}}"></script>
</head>
<body>
<div class="wrapper">
    @include('components.navbar')
    <div class="main-area">
        <div class="flex-between">
            <form method="get" action="{{route('tasks.index')}}" class="inline">
                <button type="submit" class="dark-button button-icon-flex">
                    <img src="{{asset('assets/img/icons/arrow-left.png')}}">
                    <span>
                        Список задач
                    </span>
                </button>
            </form>
            <form method="get" action="{{route('categories.create')}}">
                <button type="submit" class="dark-create-button button-icon-flex">
                    <img src="{{asset('assets/img/icons/plus.png')}}">
                    <span>
                    Новая категория
                </span>
                </button>
            </form>
        </div>
        @if(count($result->categories) == 0)
            <div class="empty-message-flex">
                <div class="empty-message">
                    Категории отсутствуют
                </div>
            </div>
        @else
            <div class="flex-center">
                <table class="list-table">
                    <thead>
                    <tr>
                        <td>
                            Название
                        </td>
                        <td>
                            Невыполненных задач
                        </td>
                        <td>
                            По приоритетам
                        </td>
                        <td></td>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($result->categories as $category)
                        <tr>
                            <td style="color: {{$category->fontColor}}; background-color: {{$category->backgroundColor}}">
                                {{$category->name}}
                            </td>
                            <td class="centered-cell">
                                {{$category->tasksCount}}
                            </td>
                            <td class="centered-cell">
                                <span class="priority-group-wrapper">
                                    <img src="{{asset('assets/img/icons/priority-high.png')}}">
                                    <span class="priority-count">
                                        {{$category->tasksCountByPriority[\App\Models\Enums\TaskPriority::HIGH->value]}}
                                    </span>
                                </span>
                                <span class="priority-group-wrapper">
                                    <img src="{{asset('assets/img/icons/priority-medium.png')}}">
                                    <span class="priority-count">
                                        {{$category->tasksCountByPriority[\App\Models\Enums\TaskPriority::MEDIUM->value]}}
                                    </span>
                                </span>
                                <span class="priority-group-wrapper">
                                    <img src="{{asset('assets/img/icons/priority-low.png')}}">
                                    <span class="priority-count">
                                        {{$category->tasksCountByPriority[\App\Models\Enums\TaskPriority::LOW->value]}}
                                    </span>
                                </span>
                            </td>
                            <td>
                                <form method="get" action="{{route('categories.edit', ['category' => $category->id])}}"
                                      class="inline">
                                    <button type="submit" class="dark-button tight-button">
                                        <img src="{{asset('assets/img/icons/edit.png')}}">
                                    </button>
                                </form>
                                <form method="post"
                                      action="{{route('categories.destroy', ['category' => $category->id])}}"
                                      class="inline">
                                    @method('DELETE')
                                    @csrf
                                    <button id="btn-delete-category-{{$category->id}}" type="button"
                                            class="dark-button tight-button ml">
                                        <img src="{{asset('assets/img/icons/delete.png')}}">
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        @endif
    </div>
</div>
</body>
</html>

resources/views/registry/tasks/tasks-list.blade.php
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title>SUETA - Список задач</title>
    <link rel="stylesheet" href="{{asset('assets/css/navbar.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/controls.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/tasks-list.css')}}">
    <link rel="shortcut icon" href="{{asset('favicon.ico')}}">
    <script type="module" src="{{asset('assets/compiled-js/tasks-list.js')}}"></script>
    <script defer src="{{asset('assets/js/lib/axios.min.js')}}"></script>
    <script defer src="{{asset('assets/js/task-finish-toggle.js')}}"></script>
</head>
<body>
<div class="wrapper">
    @include('components.navbar')
    <div class="main-area">
        <div class="flex-between">
            <form method="get" action="{{route('categories.index')}}">
                <button type="submit" class="dark-button">
                    Список категорий
                </button>
            </form>
            <div @class(['flex-right', 'hidden' => empty($categoriesList->categories)])>
                <form method="get" action="{{route('tasks.create')}}" class="inline">
                    <button type="submit" class="dark-create-button button-icon-flex mr">
                        <img src="{{asset('assets/img/icons/plus.png')}}">
                        <span>
                            Новая задача
                        </span>
                    </button>
                </form>
                <form method="post" action="{{route('tasks.delete-finished')}}">
                    @method('DELETE')
                    @csrf
                    <button id="btn-delete-finished-tasks" type="button"
                            class="dark-cancel-button button-icon-flex">
                        <img src="{{asset('assets/img/icons/trash.png')}}">
                        <span>
                            Удалить выполненные
                        </span>
                    </button>
                </form>
            </div>
        </div>
        <form name="filters" @class(['flex-center', 'hidden' => empty($categoriesList->categories)])>
            <div class="input-label mr">
                Отображать только
            </div>
            <div class="radios-list-wrapper mr">
                <div class="radio-option">
                    <input id="notFinished" type="radio" name="onlyFinished" value="0" class="dark-checkbox">
                    <label for="notFinished" class="radio-option-label">
                        Невыполненные
                    </label>
                </div>
                <div class="radio-option">
                    <input id="finished" type="radio" name="onlyFinished" value="1" class="dark-checkbox">
                    <label for="finished" class="radio-option-label">
                        Выполненные
                    </label>
                </div>
            </div>
            <div class="input-label mr">
                из категории
            </div>
            <div class="radios-list-wrapper">
                <div class="radio-option">
                    <input id="categoryId-null" type="radio" name="categoryId" value="null" class="dark-checkbox">
                    <label for="categoryId-null" class="radio-option-label">
                        Любая
                    </label>
                </div>
                @foreach($categoriesList->categories as $category)
                    <div class="radio-option">
                        <input id="categoryId{{$category->id}}" type="radio" name="categoryId"
                               value="{{$category->id}}" class="dark-checkbox">
                        <label for="categoryId{{$category->id}}" class="radio-option-label"
                               style="color: {{$category->fontColor}}; background-color: {{$category->backgroundColor}}">
                            {{$category->name}}
                        </label>
                    </div>
                @endforeach
            </div>
        </form>
        @if (empty($catalog->columns))
            <div class="empty-message-flex">
                <div class="empty-message">
                    Задачи отсутствуют
                </div>
            </div>
        @else
            <div class="flex-center">
                <div class="tasks-catalog">
                    @foreach($catalog->columns as $column)
                        <div class="column">
                            @foreach($column as $task)
                                <div class="task-card">
                                    <div class="card-controls-panel">
                                        <div id="btn-toggle-task-finished-{{$task->id}}" class="card-checkbox-wrapper">
                                            <img src="{{asset('assets/img/icons/checkmark.png')}}"
                                                @class(['checkmark-icon', 'hidden' => $task->isFinished == false])>
                                        </div>
                                        <div class="category-label"
                                             style="color: {{$task->categoryFontColor}}; background-color: {{$task->categoryBackgroundColor}}">
                                            {{$task->categoryName}}
                                        </div>
                                        @switch($task->priority)
                                            @case(\App\Models\Enums\TaskPriority::HIGH)
                                                <img src="{{asset('assets/img/icons/priority-high.png')}}">
                                                @break
                                            @case(\App\Models\Enums\TaskPriority::MEDIUM)
                                                <img src="{{asset('assets/img/icons/priority-medium.png')}}">
                                                @break
                                            @case(\App\Models\Enums\TaskPriority::LOW)
                                                <img src="{{asset('assets/img/icons/priority-low.png')}}">
                                                @break
                                        @endswitch
                                        <div>
                                            <form method="get" action="{{route('tasks.edit', ['task' => $task->id])}}"
                                                class="inline">
                                                <button type="submit" class="dark-button tight-button">
                                                    <img src="{{asset('assets/img/icons/edit.png')}}">
                                                </button>
                                            </form>
                                            <form method="post" action="{{route('tasks.destroy', ['task' => $task->id])}}"
                                                class="inline">
                                                @method('DELETE')
                                                @csrf
                                                <button id="btn-delete-task-{{$task->id}}"
                                                        type="button" class="dark-button tight-button ml">
                                                    <img src="{{asset('assets/img/icons/delete.png')}}">
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                    <div class="card-separator"></div>
                                    <div class="card-content">
                                        @isset($task->photoPreviewUrl)
                                            <a href="{{$task->photoFullSizeUrl}}" target="_blank">
                                                <img src="{{$task->photoPreviewUrl}}" class="card-image">
                                            </a>
                                        @endisset
                                        {{$task->visibleDescription}}
                                        @isset($task->hiddenDescription)
                                            <button type="button" class="dark-button show-button">
                                                ...
                                            </button>
                                            <span class="collapsible-text display-none">
                                                {{$task->hiddenDescription}}
                                            </span>
                                        @endisset
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    @endforeach
                </div>
            </div>
        @endif
    </div>
</div>
</body>
</html>